name = "Zirka"
license = "MIT"
description = "An elegant open source theme for your open source project blog."
homepage = "https://github.com/Zirkachok"
tags = ["blog", "company"]
features = ["blog", "github", "discourse","twitter"]
min_version = 0.15

[author]
  name = "Julien Beaudaux"
  homepage = "https://github.com/Zirkachok"

